server:
  port: 80
  
security:
  basic:
    enabled: false
  
#spring: 
#  datasource: 
#    url: $[sdp.flowable.db.url]
#    username: $[sdp.flowable.db.username] 
#    password: $[sdp.flowable.db.password]
#    driver-class-name: com.mysql.jdbc.Driver
#  thymeleaf:
#    mode: LEGACYHTML5
#    cache: false
    
spring:
  datasource:
    url: $[sdp.flowable.db.url]
    username: $[sdp.flowable.db.username] 
    password: $[sdp.flowable.db.password]
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    
swagger: 
  enable: true