server:
  port: 80
  
security:
  basic:
    enabled: false
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    
swagger: 
  enable: true