server:
  port: 80
  
security:
  basic:
    enabled: false
  
#spring: 
#  datasource: 
#    url: jdbc:mysql://192.168.0.116:3306/sdp_flowable?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#    username: root 
#    password: dev.123456
#    driver-class-name: com.mysql.jdbc.Driver
#  thymeleaf:
#    mode: LEGACYHTML5
#    cache: false
    
spring:
  datasource:
    url: jdbc:mysql://192.168.0.116:3306/sdp_flowable?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root 
    password: dev.123456
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    
swagger: 
  enable: true