server:
  port: 8765
spring:
  application:
    name: service-feign
eureka:
  client:
    service-url:
      default-zone: http://loclahost:8761/eureka/

feign:
  hystrix:
    enabled: ture